import 'package:equatable/equatable.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelRating {
/*
{
  "rate": 3.9,
  "count": 120
} 
*/

  double? rate;
  int? count;

  ProductModelRating({
    this.rate,
    this.count,
  });
  ProductModelRating.fromJson(Map<String, dynamic> json) {
    rate = json['rate']?.toDouble();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rate'] = rate;
    data['count'] = count;
    return data;
  }
}

class ProductModel extends Equatable {
  final int id;
  final String title;
  final double price;
  final String category;
  final String image;
  final String description;

  const ProductModel({
    required this.id,
    required this.title,
    required this.price,
    required this.category,
    required this.image,
    required this.description,
  });

  factory ProductModel.fromJson(Map<String, dynamic> json) {
    final image = _extractImage(json);
    final category = _extractCategory(json);

    return ProductModel(
      id: (json['id'] as num).toInt(),
      title: json['title']?.toString() ?? 'Untitled',
      price: (json['price'] as num?)?.toDouble() ?? 0,
      category: category,
      image: image,
      description: json['description']?.toString() ?? '',
    );
  }

  static String _extractImage(Map<String, dynamic> json) {
    final image = json['image'];
    if (image is String && image.isNotEmpty) return image;

    final images = json['images'];
    if (images is List && images.isNotEmpty) {
      final first = images.first;
      if (first is String && first.isNotEmpty) return first;
    }

    final thumbnail = json['thumbnail'];
    if (thumbnail is String && thumbnail.isNotEmpty) return thumbnail;

    return '';
  }

  static String _extractCategory(Map<String, dynamic> json) {
    final rawCategory = json['category'];
    if (rawCategory is Map && rawCategory['name'] != null) {
      return rawCategory['name'].toString();
    }
    return rawCategory?.toString() ?? 'Unknown';
  }

  @override
  List<Object?> get props => [id, title, price, category, image, description];
}